name: docker build
on: [push]
jobs:
    qemu:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                platforms: linux/arm64
