name: docker build
on: [push]
jobs:
    qemu:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                platforms: linux/arm64
            - name: checkout
              uses: actions/checkout@v3
            - name: login to github container
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
